### ISSUE TITLE
Images give away answers when downloaded

### ISSUE THREAD

**Issue by clue4** [sandboxnu/vocab-buddy#106]
**Problem:** In the assessments and activities, students can download images and obtain answers via file name - the images have "correct" or "incorrect" in their file name
**Solution:** Change the names of the images and files so that the answer is not given away. (If this doesn't work, potential other solutions include somehow disabling right click)
**Description:**
We need to make it so that even if a student downloads an image off of their activity, they still cannot tell what the answer is. Images are uploaded to our codebase via a script. 

You can view our firebase (go to firestore database) to see the how the words are stored and how the images associated with each word give away the answer. 

**Specs:**
- [ ] Find out where the images are being named as they're being uploaded (one place might be [this script here](https://github.com/sandboxnu/vocab-buddy/blob/master/uploadscript/script.js#L47))
- [ ] Change file names to something that is not as obvious to avoid giving away the answer as they're being uploaded

**If blocked:** #engineering-support, @cindy1u0 
See [this notion page](https://www.notion.so/sandboxnu/Vocab-Buddy-Reported-Bugs-17922cac823041c189795da750e2b2fe) for more information.

**Comment by dillydally414** [comment]
instead of changing the names, we could set `pointer-events: none` on the image elements - which would prevent both dragging of images as well as right clicking to save. in order to maintain any on click events, each image should then be wrapped in a div that handles the onclick callback. relevant files: [WordImages](../blob/master/frontend/src/components/WordImages.tsx), [ExpandableImage](../blob/master/frontend/src/components/ExpandableImage.tsx), [SecondActivity](../blob/master/frontend/src/pages/Interventions/SecondActivity.tsx), [ThirdActivity](../blob/master/frontend/src/pages/Interventions/ThirdActivity.tsx)
